num1 = 2
num2 = 2

try:
    x = num1 / num2
    pass
except:
    print("Error en el programa")
    pass
finally:
    print("Programa de try")